### ISSUE TITLE
Task with name 'compileScoverageScala' not found in project

### ISSUE THREAD

**Issue by nathan815** [scoverage/gradle-scoverage#133]
* scala version = 2.11
* gradlew version = 5.3.1
* gradle-scoverage version = 3.2.0

Whenever I add the plugin to build.gradle I get this error:

```
A problem occurred configuring project '***'.
> Task with name 'compileScoverageScala' not found in project '***'.
```

```
buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "gradle.plugin.org.scoverage:gradle-scoverage:3.2.0"
    }
}

apply plugin: "org.scoverage"

```

Has anyone came across this?

**Comment by eyalroth** [comment]
Could you provide more information?

What does your complete build file looks like? What command are you running?

**Comment by nathan815** [comment]
This error occurred for any gradle tasks including build, test, etc. 

It seems like it is something to do with my employer's custom build system. Unfortunately I won't be able to post the complete build files here (there are multiple), but I think I have figured it out now. Thanks!
