### ISSUE TITLE
Getting target invocation issue while running reportScoverage

### ISSUE THREAD

**Issue by vinox1992** [scoverage/gradle-scoverage#178]
Version specification:
Gradle - 5.6.1
scala version - 2.11.12
Gradle scoverage - 3.1.5

 Issue 1: unable to set plugin configuration in scoverage block.
scoverage block not populating , only scoverageclasses available .

Issue 2:  while running below command in multi module project getting java.lang.reflect.Invocation.TargetException.

gradle clean reportScoverage 

Please help us in solving both the issues.

**Comment by maiflai** [comment]
I’m sorry, this is simply too old for me to support.

stu
