### ISSUE TITLE
Scoverage 2.0

### ISSUE THREAD

**Issue by rhass** [scoverage/gradle-scoverage#181]
This is a feature request to support Scoverage 2.0

**Comment by maiflai** [comment]
@eyalroth - should we get the kotlin work in first?

**Comment by rhass** [comment]
> @eyalroth - should we get the kotlin work in first?

My unsolicited opinion on this question: Yes. 

I think switching over to kotlin would make debugging stack traces and issues a lot easier. I have yet to dig into this enough, but I suspect the issues I am having with the Scala 2.13+ multi-module projects are caused by some of the type mapping behaviors between Groovy and Scala which don't always align, which I think would be largely resolved with Kotlin, or at least easier to manage.

**Comment by gauravkumar37** [comment]
What's the complexity of completing this task? Scoverage v2 added a lot of extra support that I need in my project.

**Comment by ahmetgurbuz1** [comment]
Hi, any update on this?

**Comment by sebastian-peter** [comment]
Should be fixed by #192 now
