### ISSUE TITLE
Dependency can't be found on maven repository with version 6.0.0+

### ISSUE THREAD

**Issue by Liaomessi** [scoverage/gradle-scoverage#184]
I follow the document: [https://plugins.gradle.org/plugin/org.scoverage](https://plugins.gradle.org/plugin/org.scoverage).
Actually the maven url: [https://plugins.gradle.org/m2/gradle/plugin/org/scoverage/gradle-scoverage/](https://plugins.gradle.org/m2/gradle/plugin/org/scoverage/gradle-scoverage/) only contains the dependencies until the version 5.0.0.
How can I get the latest version dependency? 
Thank you in advance.

**Comment by maiflai** [comment]
Please check at https://plugins.gradle.org/m2/org/scoverage/org.scoverage.gradle.plugin/7.0.1 ?
