### ISSUE TITLE
Scoverage issue after gradle upgrade 

### ISSUE THREAD

**Issue by NonStopProgrammer** [scoverage/gradle-scoverage#200]
Hello Team,
Recently we have upgraded our gradle 7.5.1 to 8.2.1 since then our scala + scoverage + sonarqube build started failing with below error.

Could you please to identify the issue?

Error:
--------
Execution failed for task :reportTestScoverage
Cannot access input property sources of task reportTestScoverage. Accessing unreadable inputs or outputs is not supported. Declare the tast as untracked by using Task.doNotTrackState().
Failed to create MD5 has got file content.

Version I am using
Scala : 2.11
Sonarqube gradle plugin : 4.0.0.2929
Gradle scalatest: 0.32
Gradle scoverage: 7.0.0

**Comment by maiflai** [comment]
Sorry, I think you'll need to upgrade to a current version of this plugin to use a current version of Gradle.

Unfortunately I think you'll then also need to upgrade to Scala 2.12, which might be harder.
