### ISSUE TITLE
Could not set unknown property 'sources' for extension 'scoverage' of type org.scoverage.ScoverageExtension.

### ISSUE THREAD

**Issue by priyankabishnoi1** [scoverage/gradle-scoverage#201]
We are moving from scoverage 7.0.0 to 8.0.3, also out scala subversion is moved from 1.4.1 to 2.0.8. We were using below code in our product to get scoverage-
scoverage {
      sources = file("${sourceDir}")
      reportDir = file("${scoverageDir}/test/report")
   }
and sourceDir is /somefolder,, I see that in latest gradle-scoverage , sources is not available in ScoverageExtension.groovy
What property i can use not to restore the functionality instead of sources.

**Comment by maiflai** [comment]
Hi,

I think this was removed some time ago because the information can also be discovered by inspecting the sourceSet.

Why do you need to set it please?

Thanks,
Stu

**Comment by priyankabishnoi1** [comment]
We tried to use sourceset - 
sourceSets {
  main {
    scala.srcDirs = ["src/main/java", "src/main/scala"]
    java.srcDirs = []
  }
  scoverage {
    scala.srcDirs = ["src/main/java", "src/main/scala"]
    java.srcDirs = []
  }
  test {
    scala.srcDirs = ["src/test/java", "src/test/scala"]
    java.srcDirs = []
  }
}
But we are getting error - No source root found for '/dfolder/subproject/src/main/scala/com/ABC.scala' (source roots: '') during Scoveragereport generation.

**Comment by Tsingh315** [comment]
Hello @maiflai 
I work with the author. 
Ours is a very very customized build. 
We always had to set the sources folder explicitly.
As we upgraded from scoverage v1 to scoverage v2, we had to upgrade to the gradle-scoverage v 8.0.3.
Now we are so far, unable to set the sourceroot explicitly.
Please advise how do we set the source roots, so that it is not blank as highlighted above.

**Comment by maiflai** [comment]
You shouldn't need to touch the scoverage sourceSet.

Can you apply the scoverage plugin after modifying the main sourceSet?

**Comment by Tsingh315** [comment]
@maiflai 
We did apply the scoverage plugin set after modifying the main sourceset.

```

sourceSets {
  main {
    scala.srcDirs = ["src/main/java", "src/main/scala"]
    java.srcDirs = []
  }
  scoverage {
    scala.srcDirs = ["src/main/java", "src/main/scala"]
    java.srcDirs = []
  }
  test {
    scala.srcDirs = ["src/test/java", "src/test/scala"]
    java.srcDirs = []
  }
}


apply plugin: "java"
apply plugin: "scala"
apply plugin: 'wd-xray'
apply plugin: "jacoco"
apply plugin: 'com.form.diff-coverage'
apply plugin: 'org.scoverage'
```
It still gives the same error

**Comment by Tsingh315** [comment]
@maiflai One thing we forgot to mention but may be relevant is that we are on scala version 2.12.17 and using scoverage version is 2.0.8

**Comment by Tsingh315** [comment]
@maiflai I think I understand now that I should not be setting the scoverage source set. I am trying without it

**Comment by maiflai** [comment]
you might check https://github.com/scoverage/gradle-scoverage/blob/master/src/functionalTest/resources/projects/scala-java-multi-module/mixed_scala_java/build.gradle#L11 which has something similar?

**Comment by Tsingh315** [comment]
@maiflai I was able to set the sources root using the method described in your last comment. However, it still complained of not finding the sources for scala code.

**Comment by maiflai** [comment]
Sorry, if you are unable to share the project that is failing, please could you construct a simple reproducible failure for analysis? 

Thanks,
Stu
