### ISSUE TITLE
code coverage generation failing when using gradle plugin 8.0.3

### ISSUE THREAD

**Issue by MuthuVignesh91** [scoverage/gradle-scoverage#204]
When trying to generate scoverage.xml the task is failing

command:
./gradlew reportScoverage

Error:
`./gradlew reportScoverage           
> Task :cap-gds:extractIncludeScoverageProto FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cap-gds:extractIncludeScoverageProto'.
> Could not resolve all dependencies for configuration ':cap-gds:scoverage'.
   > Could not find org.scoverage:scalac-scoverage-plugin_2.13.12:2.0.8.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/scoverage/scalac-scoverage-plugin_2.13.12/2.0.8/scalac-scoverage-plugin_2.13.12-2.0.8.pom
       - https://repo.akka.io/maven/org/scoverage/scalac-scoverage-plugin_2.13.12/2.0.8/scalac-scoverage-plugin_2.13.12-2.0.8.pom
     Required by:
         project :cap-gds

* Try:
> The project declares repositories, effectively ignoring the repositories you have declared in the settings.
   You can figure out how project repositories are declared by configuring your build to fail on project repositories.
   For more information, please refer to https://docs.gradle.org/8.3/userguide/declaring_repositories.html#sub:fail_build_on_project_repositories in the Gradle documentation.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 1s
31 actionable tasks: 5 executed, 26 up-to-date
`

**Comment by maiflai** [comment]
It seems that the upstream scoverage scalac plugin 2.0.8 is not published for the newer scala compiler version 2.13.12.

Please configure your build to use a version that has been published? I think that 2.1.1 is the current release version.

https://repo.maven.apache.org/maven2/org/scoverage/scalac-scoverage-plugin_2.13.12/maven-metadata.xml

```groovy
scoverage.scoverageVersion = '2.1.1'
```

**Comment by MuthuVignesh91** [comment]
@maiflai, it worked when added the scoverage.scoverageVersion as part of the configuration. But isn't it supposed to be working by default?

**Comment by maiflai** [comment]
Sorry, I'm not sure that benefit outweighs cost.

If you are upgrading your scala compiler version then currently the upstream scoverage scala compiler plugin version also needs to change, but this doesn't require that I publish a new version of this plugin because the gradle plugin is (generally) forward-compatible.

I think you still have to change your build regardless, whether or not I publish a new version of this plugin.

The change is either

```
...
    id 'org.scoverage' version '8.0.X+1'
...
```

or 

```
scoverage.scoverageVersion = '2.1.X+1'
```

I think the second is more explicit as to the exact change involved.

You might consider asking the upstream maintainers to publish old versions for new scalac versions, and then neither you nor I would need to change anything related to scoverage?

Stu,

**Comment by MuthuVignesh91** [comment]
Noted with tanks. This issue can be clsoed
