### ISSUE TITLE
Is there any way to turn off highlighting?

### ISSUE THREAD

**Issue by melodious** [scoverage/gradle-scoverage#30]
Highlighting (-Yrangepos) is causing this error:
```
uncaught exception during compilation: scala.tools.nsc.interactive.RangePositions$ValidateException
Overlapping trees (42014,42009)
```
I see the property in ScoverageExtension.groovy but don't see any way to configure it. 

Please see https://issues.scala-lang.org/browse/SI-8596 for more information of the bug.

The plugin is completely broken for me right now. 
Thanks.

**Comment by maiflai** [comment]
Hi,

That link says that this bug was resolved in 2.11.2, I suggest you upgrade to the latest version of scala.

If that doesn't work, then this configuration should help?

```groovy
scoverage {
    highlighting = false
}
```

Thanks,
Stu.

**Comment by melodious** [comment]
Thanks. Unfortunately upgrading scala is not an option but that did turn off the highlighting. Now I am getting a different error which I have no idea of the cause: 
```
ConstantType(value = Constant(2181))
uncaught exception during compilation: java.lang.NoSuchMethodError
```

**Comment by melodious** [comment]
Nevermind the previous error. I was using the wrong version of the plugin. All is fixed now. Thanks!
