### ISSUE TITLE
Build fails and stops if a test fails during testScoverage step

### ISSUE THREAD

**Issue by SinghAsDev** [scoverage/gradle-scoverage#31]
If a test fails during testScoverage step, the step fails and causes the build to fail. Using "--continue" did not help either.

**Comment by maiflai** [comment]
I imagine that `--continue` might not work for your `kafka` project because it uses the `GradleBuildTask` internally, and it probably doesn't pass that command line argument through.

An alternative might be to configure the test task to ignore failures:

```
testScoverage {
  ignoreFailures = true
}
```

**Comment by SinghAsDev** [comment]
@maifai thanks! it works with your suggestion. Closing the issue.
