### ISSUE TITLE
Is there any way to turn off parallel execution for the tests?

### ISSUE THREAD

**Issue by melodious** [scoverage/gradle-scoverage#32]
My tests cannot run in parallel. How can I configure this?

Thanks!

**Comment by maiflai** [comment]
gradle-scoverage should use the default behaviour.

http://www.gradle.org/docs/current/dsl/org.gradle.api.tasks.testing.Test.html says that for the java plugin (and I think hence the scala plugin) the default behaviour is to not run tests in parallel. 

You might want to force the matter by explicitly configuring all the test tasks?

```
tasks.withType(Test)  {
  maxParallelForks = 1
}
```

**Comment by melodious** [comment]
I don't run all test tasks with maxParallelForks = 1 since I have some specialized test tasks that I run parallel. I can experiment with whether or not the custom test tasks can override this property without issue. For now, I have set it this way:
```
    project.compileScala.scalaCompileOptions.additionalParameters += '-D-PS'
```

**Comment by maiflai** [comment]
That looks rather curious to me - are you modifying the compilation of your main source code to configure the running of tests? 

Have you written your own test runner in `src/main` or perhaps you're using the scalatest Runner directly?

I don't think there is a difference between 
`scoverage { project.compileScala.scalaCompileOptions.additionalParameters += '-D-PS' }`
and 
`compileScala { scalaCompileOptions { additionalParameters += '-D-PS'  } }`

If you are using a normal runner, and want to configure the exact test task, you can configure it directly:

```
test {
  maxParallelForks = 1
  // or if you want to pass a system property
  systemProperty 'some.prop', 'value'
}
```

or if you want to configure the task that this plugin creates to run tests against instrumented code

```
testScoverage {
  maxParallelForks = 1
}
```

**Comment by melodious** [comment]
You're right, it could be problematic. The last option 
```
testScoverage {
  maxParallelForks = 1
} 
```
is exactly what I need. Thanks!
