### ISSUE TITLE
checkScoverage is checking line coverage, not statement coverage

### ISSUE THREAD

**Issue by Kwestor** [scoverage/gradle-scoverage#38]
As in summary. Main idea of scoverage **is** to calculate statement coverage, as line coverage in Scala is not a reliable statistics.

I understand existing clients depends on current behavior, but I think gradle plugin should at least provide ability to change this behavior.

We can either read `statement-rate="0.00" branch-rate="0.00"` from `scoverage.xml` file, or run testCoverage task and read it from there (like [sbt plugin](https://github.com/scoverage/sbt-scoverage/blob/master/src/main/scala/scoverage/ScoverageSbtPlugin.scala#L229)).

**Comment by maiflai** [comment]
Yes, this is based on the old SCCT output which was cobertura-based.

I think I prefer reading from the scoverage xml file, rather than using the Scala API?

**Comment by Kwestor** [comment]
It's ok. I'll implement this one and create a PR.
