### ISSUE TITLE
Aggregation does not generate scoverage.xml

### ISSUE THREAD

**Issue by Quizzie** [scoverage/gradle-scoverage#45]
The aggregateScoverage task generates a cobertura.xml file and the HTML files, but not the scoverage.xml file in the build/scoverage-aggregate directory.

It should be fixed by adding a ScoverageXmlWriter to the AggregateReportApp.java file.

**Comment by Kwestor** [comment]
There is a PR with a lot of fixes to aggregate task: https://github.com/scoverage/gradle-scoverage/pull/42/commits, but it stuck.

**Comment by sksamuel** [comment]
I've ping the author of the plugin.

**Comment by maiflai** [comment]
Sorry for the delay, I'll take a look this weekend.

**Comment by maiflai** [comment]
I've released 1.0.9 which should publish the scoverage file by default - please could you check?

Thanks,
Stu

**Comment by Quizzie** [comment]
Yes, it works. Thank you.

You might want to add this note to the readme:
For checking coverage of the aggregated result, configure the checkScoverage task:

     checkScoverage {
	     reportDir = file("$buildDir/scoverage-aggregate/")
     }

**Comment by maiflai** [comment]
I've updated the docs, thanks
