### ISSUE TITLE
java.lang.NoSuchMethodError: scala.reflect.internal.Trees$DefDef.name()Lscala/reflect/internal/Names

### ISSUE THREAD

**Issue by vikramkone** [scoverage/gradle-scoverage#49]
hi,
I'm trying to enable gradle-scoverage plugin on my multi module project which has a mix of java and scala sub projects.
My root build.gradle file looks like this

buildscript {
   repositories {
      jcenter()
   }
   dependencies {
      classpath 'org.scoverage:gradle-scoverage:1.0.9'
   }
}

allprojects{
    apply plugin: 'idea'
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'jacoco'
    apply plugin: 'scoverage'

    repositories {
        jcenter()
    }

jacocoTestReport {
    reports {
        xml.enabled true
        csv.enabled true
        html.enabled true
    }
}

    dependencies {
        compile group: 'joda-time', name: 'joda-time', version:'2.8.2'
        testCompile group: 'junit', name: 'junit', version:'4.12'
        scoverage 'org.scoverage:scalac-scoverage-plugin_2.11:1.1.1', 'org.scoverage:scalac-scoverage-runtime_2.11:1.1.1'
    }
}

When I run gradle clean build compileScoverageScala testScoverage from the root project, I'm seeing the following error. Any idea why?

:spark-jobs:compileScoverageScala
[ant:scalac] java.lang.NoSuchMethodError: scala.reflect.internal.Trees$DefDef.name()Lscala/reflect/internal/Names$TermName;
[ant:scalac]    at scoverage.ScoverageInstrumentationComponent$Transformer.process(plugin.scala:407)
[ant:scalac]    at scoverage.ScoverageInstrumentationComponent$Transformer$$anonfun$transformStatements$1.apply(plugin.scala:143)
[ant:scalac]    at scoverage.ScoverageInstrumentationComponent$Transformer$$anonfun$transformStatements$1.apply(plugin.scala:143)
[ant:scalac]    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[ant:scalac]    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[ant:scalac]    at scala.collection.immutable.List.foreach(List.scala:318)
[ant:scalac]    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
[ant:scalac]    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
[ant:scalac]    at scoverage.ScoverageInstrumentationComponent$Transformer.transformStatements(plugin.scala:143)
[ant:scalac]    at scoverage.ScoverageInstrumentationComponent$Transformer.process(plugin.scala:549)
[ant:scalac]    at scoverage.ScoverageInstrumentationComponent$Transformer.transform(plugin.scala:141)
[ant:scalac]    at scoverage.ScoverageInstrumentationComponent$Transformer.transform(plugin.scala:103)
[ant:scalac]    at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2904)
[ant:scalac]    at scala.reflect.internal.Trees$$anonfun$itransform$5.apply(Trees.scala:1285)
[ant:scalac]    at scala.reflect.internal.Trees$$anonfun$itransform$5.apply(Trees.scala:1284)
[ant:scalac]    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
[ant:scalac]    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
[ant:scalac]    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
[ant:scalac]    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:19)
[ant:scalac]    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1283)
[ant:scalac]    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
[ant:scalac]    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
[ant:scalac]    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
[ant:scalac]    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:48)
[ant:scalac]    at scoverage.ScoverageInstrumentationComponent$Transformer.process(plugin.scala:462)
[ant:scalac]    at scoverage.ScoverageInstrumentationComponent$Transformer$$anonfun$transformStatements$1.apply(plugin.scala:143)
[ant:scalac]    at scoverage.ScoverageInstrumentationComponent$Transformer$$anonfun$transformStatements$1.apply(plugin.scala:143)
[ant:scalac]    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[ant:scalac]    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[ant:scalac]    at scala.collection.immutable.List.foreach(List.scala:318)
[ant:scalac]    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
[ant:scalac]    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
[ant:scalac]    at scoverage.ScoverageInstrumentationComponent$Transformer.transformStatements(plugin.scala:143)
[ant:scalac]    at scoverage.ScoverageInstrumentationComponent$Transformer.process(plugin.scala:498)
[ant:scalac]    at scoverage.ScoverageInstrumentationComponent$Transformer.transform(plugin.scala:141)
[ant:scalac]    at scoverage.ScoverageInstrumentationComponent$Transformer.transform(plugin.scala:103)
[ant:scalac]    at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:227)
[ant:scalac]    at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
[ant:scalac]    at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:464)
[ant:scalac]    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:431)
[ant:scalac]    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:431)
[ant:scalac]    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
[ant:scalac]    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
[ant:scalac]    at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:431)
[ant:scalac]    at scoverage.ScoverageInstrumentationComponent$$anon$1.run(plugin.scala:92)
[ant:scalac]    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1583)
[ant:scalac]    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1557)
[ant:scalac]    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1553)
[ant:scalac]    at scala.tools.nsc.Global$Run.compile(Global.scala:1662)
[ant:scalac]    at scala.tools.ant.Scalac.executeInternal(Scalac.scala:699)
[ant:scalac]    at scala.tools.ant.Scalac.execute(Scalac.scala:647)
[ant:scalac]    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[ant:scalac]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ant:scalac]    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ant:scalac]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ant:scalac]    at java.lang.reflect.Method.invoke(Method.java:497)
[ant:scalac]    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[ant:scalac]    at groovy.util.AntBuilder.performTask(AntBuilder.java:327)
[ant:scalac]    at groovy.util.AntBuilder.nodeCompleted(AntBuilder.java:272)
[ant:scalac]    at org.gradle.api.internal.project.ant.BasicAntBuilder.nodeCompleted(BasicAntBuilder.java:78)
[ant:scalac]    at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
[ant:scalac]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ant:scalac]    at java.lang.reflect.Method.invoke(Method.java:497)
[ant:scalac]    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:233)
[ant:scalac]    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
[ant:scalac]    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
[ant:scalac]    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:58)
[ant:scalac]    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
[ant:scalac]    at org.gradle.api.internal.project.antbuilder.AntBuilderDelegate.nodeCompleted(AntBuilderDelegate.groovy:80)
[ant:scalac]    at groovy.util.BuilderSupport.doInvokeMethod(BuilderSupport.java:149)
[ant:scalac]    at groovy.util.BuilderSupport.invokeMethod(BuilderSupport.java:66)
[ant:scalac]    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:430)
[ant:scalac]    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:371)
[ant:scalac]    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrentN(ScriptBytecodeAdapter.java:82)
[ant:scalac]    at org.gradle.api.internal.tasks.scala.AntScalaCompiler$_execute_closure1.doCall(AntScalaCompiler.groovy:61)
[ant:scalac]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ant:scalac]    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ant:scalac]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ant:scalac]    at java.lang.reflect.Method.invoke(Method.java:497)
[ant:scalac]    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
[ant:scalac]    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
[ant:scalac]    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
[ant:scalac]    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
[ant:scalac]    at groovy.lang.Closure.call(Closure.java:426)
[ant:scalac]    at groovy.lang.Closure.call(Closure.java:442)
[ant:scalac]    at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
[ant:scalac]    at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
[ant:scalac]    at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:91)
[ant:scalac]    at org.gradle.api.internal.project.antbuilder.DefaultIsolatedAntBuilder$3.execute(DefaultIsolatedAntBuilder.java:178)
[ant:scalac]    at org.gradle.api.internal.project.antbuilder.DefaultIsolatedAntBuilder$3.execute(DefaultIsolatedAntBuilder.java:160)
[ant:scalac]    at org.gradle.api.internal.project.antbuilder.ClassPathToClassLoaderCache.withCachedClassLoader(ClassPathToClassLoaderCache.java:139)
[ant:scalac]    at org.gradle.api.internal.project.antbuilder.DefaultIsolatedAntBuilder.execute(DefaultIsolatedAntBuilder.java:154)
[ant:scalac]    at org.gradle.api.internal.project.IsolatedAntBuilder$execute$0.call(Unknown Source)
[ant:scalac]    at org.gradle.api.internal.tasks.scala.AntScalaCompiler.execute(AntScalaCompiler.groovy:58)
[ant:scalac]    at org.gradle.api.internal.tasks.scala.AntScalaCompiler.execute(AntScalaCompiler.groovy)
[ant:scalac]    at org.gradle.api.internal.tasks.scala.DefaultScalaJavaJointCompiler.execute(DefaultScalaJavaJointCompiler.java:35)
[ant:scalac]    at org.gradle.api.internal.tasks.scala.DefaultScalaJavaJointCompiler.execute(DefaultScalaJavaJointCompiler.java:25)
[ant:scalac]    at org.gradle.api.internal.tasks.scala.NormalizingScalaCompiler.delegateAndHandleErrors(NormalizingScalaCompiler.java:101)
[ant:scalac]    at org.gradle.api.internal.tasks.scala.NormalizingScalaCompiler.execute(NormalizingScalaCompiler.java:52)
[ant:scalac]    at org.gradle.api.internal.tasks.scala.NormalizingScalaCompiler.execute(NormalizingScalaCompiler.java:38)
[ant:scalac]    at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:34)
[ant:scalac]    at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
[ant:scalac]    at org.gradle.language.scala.tasks.AbstractScalaCompile.compile(AbstractScalaCompile.java:75)
[ant:scalac]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ant:scalac]    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ant:scalac]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ant:scalac]    at java.lang.reflect.Method.invoke(Method.java:497)
[ant:scalac]    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
[ant:scalac]    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:227)
[ant:scalac]    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
[ant:scalac]    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
[ant:scalac]    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
[ant:scalac]    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
[ant:scalac]    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
[ant:scalac]    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
[ant:scalac]    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
[ant:scalac]    at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
[ant:scalac]    at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
[ant:scalac]    at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
[ant:scalac]    at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
[ant:scalac]    at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
[ant:scalac]    at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
[ant:scalac]    at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
[ant:scalac]    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
[ant:scalac]    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
[ant:scalac]    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:62)
[ant:scalac]    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
[ant:scalac]    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
[ant:scalac]    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
[ant:scalac]    at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
[ant:scalac]    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
[ant:scalac]    at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
[ant:scalac]    at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
[ant:scalac]    at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
[ant:scalac]    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
[ant:scalac]    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
[ant:scalac]    at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
[ant:scalac]    at org.gradle.internal.Factories$1.create(Factories.java:22)
[ant:scalac]    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
[ant:scalac]    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
[ant:scalac]    at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
[ant:scalac]    at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
[ant:scalac]    at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
[ant:scalac]    at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
[ant:scalac]    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
[ant:scalac]    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
[ant:scalac]    at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
[ant:scalac]    at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
[ant:scalac]    at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
[ant:scalac]    at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
[ant:scalac]    at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
[ant:scalac]    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
[ant:scalac]    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
[ant:scalac]    at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
[ant:scalac]    at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
[ant:scalac]    at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
[ant:scalac]    at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
[ant:scalac]    at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
[ant:scalac]    at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
[ant:scalac]    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
[ant:scalac]    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
[ant:scalac]    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
[ant:scalac]    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
[ant:scalac]    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
[ant:scalac]    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
[ant:scalac]    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
[ant:scalac]    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
[ant:scalac]    at org.gradle.launcher.Main.doAction(Main.java:33)
[ant:scalac]    at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
[ant:scalac]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ant:scalac]    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ant:scalac]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ant:scalac]    at java.lang.reflect.Method.invoke(Method.java:497)
[ant:scalac]    at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
[ant:scalac]    at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
[ant:scalac]    at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
:spark-jobs:compileScoverageScala FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':spark-jobs:compileScoverageScala'.
> Compile failed because of an internal compiler error (scala.reflect.internal.Trees$DefDef.name()Lscala/reflect/internal/Names$TermName;); see the error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by maiflai** [comment]
I suspect that you have incompatible Scala dependencies.

Please could you share the whole build.gradle for the `spark-jobs` project?

I'd also like to see the command that was passed to the scala compiler - could you perhaps run the build again with `--info` and share the output?

Thanks,
Stu.

**Comment by vikramkone** [comment]
Here is the build.gradle file for spark-jobs project

apply plugin: 'scala'
description = 'Spark Jobs for Weve'
// This tells gradle to use its built in compiler rather than Ant
tools. If you don't do this then you will get warnings about
// deprecated target VMs when compiling the scala
compileScala.scalaCompileOptions.useAnt = false
repositories {
    flatDir {
        dirs 'lib'
    }
}
dependencies {
    compile group: 'org.scala-lang', name: 'scala-library', version:'2.10.5'
    compile group: 'org.apache.spark', name: 'spark-core_2.10', version:'1.4.1'
    compile group: 'org.apache.spark', name: 'spark-streaming_2.10',
version:'1.4.1'
    compile group: 'org.apache.spark', name:
'spark-streaming-kafka_2.10', version:'1.4.1'
    compile group: 'com.datastax.spark', name:
'spark-cassandra-connector_2.10', version:'1.4.0'
    compile group: 'org.apache.kafka', name: 'kafka_2.10', version:'0.8.2.1'
    compile group: 'org.apache.logging.log4j', name: 'log4j-core', version:'2.4'
    compile group: 'com.fasterxml.jackson.module', name:
'jackson-module-scala_2.10', version:'2.4.4'
    testCompile group: 'org.scalatest', name: 'scalatest_2.10', version:'2.2.1'
    compile name: 'dse'
    compile name: 'data-flow-contract'
}

**Comment by maiflai** [comment]
It looks like your root project configures Scoverage for Scala 2.11, but `spark-jobs` is using Scala 2.10.

If all your projects use Scala 2.10 then please could you try changing the `subprojects` scoverage dependency to the following?

```groovy
scoverage 'org.scoverage:scalac-scoverage-plugin_2.10:1.1.1', 'org.scoverage:scalac-scoverage-runtime_2.10:1.1.1'
```

Thanks,
Stu

**Comment by vikramkone** [comment]
That worked. Thanks! BTW, I had a quick Q...Can scoverage plugin be applied only to the subproject that has scala code? or does it need to be applied at the root level? I only have one sub project that uses scala..rest all have java code and are covered by jacoco

**Comment by maiflai** [comment]
Please can I close this issue?

**Comment by vikramkone** [comment]
Yes please. Thanks
