### ISSUE TITLE
scoverage on scalatest for java main source failed

### ISSUE THREAD

**Issue by kknd22** [scoverage/gradle-scoverage#51]
we have java source and use scalatest, which works fine. However, I have trouble to make scoverage work - the scoverage.xml is never generated. Can someone help?

**Comment by maiflai** [comment]
Hi,

Sorry, scoverage only instruments scala code. Have you tried the Jacoco plugin?

Thanks,
Stu.

**Comment by maiflai** [comment]
Please can I close this issue?

**Comment by kknd22** [comment]
Sure thank for the fast help.
