### ISSUE TITLE
compileScoverageScala looking for source in wrong directory

### ISSUE THREAD

**Issue by coryfklein** [scoverage/gradle-scoverage#52]
Here is a sample of the output from `./gradlew --debug compileScoverageScala` (emphasis added)

> 13:39:18.951 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :davinci-model:compileScoverageScala (Thread[Daemon worker Thread 25,5,main]) started.
> 13:39:18.951 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :davinci-model:compileScoverageScala
> 13:39:18.951 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':davinci-model:compileScoverageScala'
> 13:39:18.951 [INFO] [org.gradle.api.internal.file.collections.DirectoryFileTree] file or directory **'/Users/coryklein/davinci/davinci-model/src/scoverage/scala'**, not found
> 13:39:18.952 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':davinci-model:compileScoverageScala' is up-to-date
> // SNIP
> 13:39:18.964 [INFO] [org.gradle.api.internal.file.collections.DirectoryFileTree] file or directory **'/Users/coryklein/davinci/davinci-model/src/scoverage/scala'**, not found
> 13:39:18.965 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] **Skipping task ':davinci-model:compileScoverageScala' as it is up-to-date (took 0.013 secs).**
> 13:39:18.965 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':davinci-model:compileScoverageScala'
> 13:39:18.965 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :davinci-model:compileScoverageScala UP-TO-DATE

The `compileScoverageScala` task is not running because it is considered up to date, and it is considered up to date because it cannot find a directory.

You can see that scoverage is looking in the module directory `src/scoverage/scala` for something (probably code I assume). It can't find that directory because it doesn't exist, because of course my code is in `src/main/scala`. I can't seem to find any direction as how to specify to the plugin that my code is in `src/main/scala`.

Why is it looking for it there? Is this an indication that I have something else that is wrong?

**Comment by coryfklein** [comment]
I've also asked about this on StackOverflow in [much more detail](http://stackoverflow.com/questions/34053762/scoverage-generates-no-reports-for-project).

**Comment by maiflai** [comment]
I think that's a red herring; it's an artifact of wanting to produce the classes into a scoverage directory.

testScoverageClasses is another artifact, it should produce no output because I didn't think there was much value in measuring code coverage of test sources.

Sorry, it's late here but I'll try to take a look tomorrow.

In the meantime can you share the project in its entirety? I appreciate that might not be possible.

You might try running the clean task before trying again. Gradle is quite eager to not redo work, so you may find that the first testScoverage did all the work and reruns are just being skipped.

**Comment by maiflai** [comment]
You also need to run reportScoverage to see reports; testing just gathers measurements.

**Comment by coryfklein** [comment]
Unfortunately, I can't share the source. If we can't figure it out without the source I may have to create a "smallest reproducible example", but if you have any tips before then I would like to go that route first.

Did a `./gradlew clean` then `./gradlew testScoverage` and here's the output:

```
:davinci-server:compileScoverageJava UP-TO-DATE
:davinci-server:compileScoverageScala
:davinci-server:processScoverageResources UP-TO-DATE
:davinci-server:scoverageClasses
:davinci-server:compileTestScoverageJava UP-TO-DATE
:davinci-server:compileTestScoverageScala
[ant:scalac] Element '/Users/coryklein/domo/davinci/davinci-server/build/resources/scoverage' does not exist.
:davinci-server:processTestScoverageResources UP-TO-DATE
:davinci-server:testScoverageClasses
:davinci-server:testScoverage

BUILD SUCCESSFUL
```

Then followed that up with a `./gradlew reportScoverage`:

```
:davinci-server:compileScoverageJava UP-TO-DATE
:davinci-server:compileScoverageScala UP-TO-DATE
:davinci-server:processScoverageResources UP-TO-DATE
:davinci-server:scoverageClasses UP-TO-DATE
:davinci-server:compileTestScoverageJava UP-TO-DATE
:davinci-server:compileTestScoverageScala UP-TO-DATE
:davinci-server:processTestScoverageResources UP-TO-DATE
:davinci-server:testScoverageClasses UP-TO-DATE
:davinci-server:testScoverage UP-TO-DATE
:davinci-server:reportScoverage SKIPPED

BUILD SUCCESSFUL
```

`reportScoverage` is still getting skipped.

After doing more searching, here are some files being generated that may be related:

* `davinci-server/build/classes/scoverage` is still getting populated with all the compiled `.class` files from my project.
* `davinci-server/build/test-results/binary/testScoverage` has `output.bin`, `output.bin.idx`, and `results.bin`.
* `davinci-server/build/tmp/testScoverage/jar_extract_7348647597045608008_tmp` exists
* `davinci-server/build/reports/tests/` has `index.html`, `js/report.js`, `css/style.css`, and `css/base-style.css`, but I *think* this is unrelated to scoverage.

**Comment by maiflai** [comment]
This may sound silly, but are there actually any tests being run in this project?

The report task is skipped when no measurements have been made. Measurements are made when instrumented code is executed. 

Do you see any test results in that html report?

**Comment by coryfklein** [comment]
I don't have any tests that legitimately exercise code. I have two test classes that look just like this:

```scala
package com.domo.davinci.render

import org.testng.Assert
import org.testng.annotations.Test

/**
 * Created by Cory Klein on 2015-09-03.
 */

class RendererTest {
  @Test
  def testNothing() = {
    Assert.assertTrue(true)
  }
}
```

And the test report looks like this:
![image](https://cloud.githubusercontent.com/assets/3503322/11566118/47a2e6ce-999e-11e5-87b8-303baa5265dc.png)

> The report task is skipped when no measurements have been made. Measurements are made when instrumented code is executed.

Ah. This may be the clue than. I assumed I would still get a report but it would just say "0% statement coverage". This may also explain an error I have seen though can't remember how to reproduce, it said something about no Statements existing or being unable to find a Statement or something like that.

**Comment by coryfklein** [comment]
Ah, here it is:

```
➜  davinci git:(socket-timeout-testing) ✗ gw :davinci-server:checkScoverage
:davinci-server:findMainClass
:davinci-server:compileScoverageJava UP-TO-DATE
:davinci-server:compileScoverageScala UP-TO-DATE
:davinci-server:processScoverageResources UP-TO-DATE
:davinci-server:scoverageClasses UP-TO-DATE
:davinci-server:compileTestScoverageJava UP-TO-DATE
:davinci-server:compileTestScoverageScala UP-TO-DATE
:davinci-server:processTestScoverageResources UP-TO-DATE
:davinci-server:testScoverageClasses UP-TO-DATE
:davinci-server:testScoverage UP-TO-DATE
:davinci-server:reportScoverage SKIPPED
:davinci-server:checkScoverage FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':davinci-server:checkScoverage'.
> Coverage file (type: Statement) not found, check your configuration.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by coryfklein** [comment]
Tried creating a dummy `multiply` method in one of my classes and then created a test that exercises it:

```scala
  @Test
  def testMultiply() = {
    Assert.assertEquals(renderService.multiply(5, 4), 20)
  }
```

And still getting the same error regarding the `Statement` not found.

Looking back at the main page on scoverage, it does say:

**Comment by coryfklein** [comment]
Tried swapping in JUnit in place of TestNG, still same error. Hmm.

**Comment by coryfklein** [comment]
At least now I have tests in the `davinci-server/build/reports/tests/index.html` report though.

![image](https://cloud.githubusercontent.com/assets/3503322/11567258/6b217e80-99a3-11e5-9336-3c253c7fe589.png)

**Comment by maiflai** [comment]
re: JUnit / TestNG, I don't think it really matters.

You do have to tell Gradle that you want it to run a particular test framework though, and I think it defaults to JUnit.

Good to see you have test output now. Did you see any measurement files in `davinci-server/build/scoverage`?

Please can you run a clean build in that project and let me know the full output?

```bash
gw -i -p davinci-server clean reportScoverage
```

**Comment by coryfklein** [comment]
Output of `gw -i -p davinci-server clean reportScoverage` is on pastebin [here](http://pastebin.com/ypCr3kL3).

One thing to note, my project has three modules `davinci-client`, `davinci-model`, and `davinci-server`. In order to be succinct in our discussion here, I have only been showing info for the `davinci-server` module, but the above output on pastebin will show info for the other two modules in the gradle project as well.

> Good to see you have test output now. Did you see any measurement files in davinci-server/build/scoverage?

I don't have a `davinci-server/build/scoverage` directory.

This search does appear to display all of the scoverage related files though.

```
➜  davinci git:(socket-timeout-testing) ✗ find davinci-server -name "*overage*" | xargs find
davinci-server/build/classes/scoverage
davinci-server/build/classes/scoverage/com
davinci-server/build/classes/scoverage/com/domo
davinci-server/build/classes/scoverage/com/domo/davinci
davinci-server/build/classes/scoverage/com/domo/davinci/configuration
davinci-server/build/classes/scoverage/com/domo/davinci/configuration/DaVinciModuleConfiguration$$anonfun$1.class
davinci-server/build/classes/scoverage/com/domo/davinci/configuration/DaVinciModuleConfiguration$$anonfun$objectPool$1.class
davinci-server/build/classes/scoverage/com/domo/davinci/configuration/DaVinciModuleConfiguration$$anonfun$objectPool$2.class
davinci-server/build/classes/scoverage/com/domo/davinci/configuration/DaVinciModuleConfiguration.class
davinci-server/build/classes/scoverage/com/domo/davinci/DaVinciBanner.class
davinci-server/build/classes/scoverage/com/domo/davinci/DaVinciConstants$.class
davinci-server/build/classes/scoverage/com/domo/davinci/DaVinciConstants.class
davinci-server/build/classes/scoverage/com/domo/davinci/DaVinciService$.class
davinci-server/build/classes/scoverage/com/domo/davinci/DaVinciService$delayedInit$body.class
davinci-server/build/classes/scoverage/com/domo/davinci/DaVinciService.class
davinci-server/build/classes/scoverage/com/domo/davinci/exception
davinci-server/build/classes/scoverage/com/domo/davinci/exception/ServiceUnavailableException$.class
davinci-server/build/classes/scoverage/com/domo/davinci/exception/ServiceUnavailableException.class
davinci-server/build/classes/scoverage/com/domo/davinci/pool
davinci-server/build/classes/scoverage/com/domo/davinci/pool/WebDriverPooledObjectFactory.class
davinci-server/build/classes/scoverage/com/domo/davinci/render
davinci-server/build/classes/scoverage/com/domo/davinci/render/RenderResource$$anonfun$dbTest$1$$anonfun$apply$1.class
davinci-server/build/classes/scoverage/com/domo/davinci/render/RenderResource$$anonfun$dbTest$1.class
davinci-server/build/classes/scoverage/com/domo/davinci/render/RenderResource.class
davinci-server/build/classes/scoverage/com/domo/davinci/render/RenderService$$anonfun$1.class
davinci-server/build/classes/scoverage/com/domo/davinci/render/RenderService$$anonfun$2.class
davinci-server/build/classes/scoverage/com/domo/davinci/render/RenderService$$anonfun$3.class
davinci-server/build/classes/scoverage/com/domo/davinci/render/RenderService.class
davinci-server/build/classes/testScoverage
davinci-server/build/classes/testScoverage/com
davinci-server/build/classes/testScoverage/com/domo
davinci-server/build/classes/testScoverage/com/domo/davinci
davinci-server/build/classes/testScoverage/com/domo/davinci/render
davinci-server/build/classes/testScoverage/com/domo/davinci/render/RendererTest.class
davinci-server/build/classes/testScoverage/com/domo/davinci/render/RendererTestIT.class
davinci-server/build/test-results/binary/testScoverage
davinci-server/build/test-results/binary/testScoverage/output.bin
davinci-server/build/test-results/binary/testScoverage/output.bin.idx
davinci-server/build/test-results/binary/testScoverage/results.bin
davinci-server/build/tmp/compileScoverageScala
davinci-server/build/tmp/compileTestScoverageScala
```

**Comment by maiflai** [comment]
Thanks for posting the log - I would expect to see something like the following lines:

>Compiling with Ant scalac task.
[ant:scalac] Compiling 1 source file to /Users/stu/Documents/Eclipse/gradle-scoverage-sample/single/build/classes/scoverage
[ant:scalac] Compiling 1 source file to /Users/stu/Documents/Eclipse/gradle-scoverage-sample/single/build/classes/scoverage
[ant:scalac] [info] Cleaning datadir [/Users/stu/Documents/Eclipse/gradle-scoverage-sample/single/build/scoverage]
[ant:scalac] [info] Beginning coverage instrumentation
[ant:scalac] [info] Instrumentation completed [1 statements]
[ant:scalac] [info] Wrote instrumentation file [/Users/stu/Documents/Eclipse/gradle-scoverage-sample/single/build/scoverage/scoverage.coverage.xml]
[ant:scalac] [info] Will write measurement data to [/Users/stu/Documents/Eclipse/gradle-scoverage-sample/single/build/scoverage]

However, I just see the standard `ant:scalac` messages in your build log.

Can you please turn up the logging on the compilation task as follows:

```groovy
compileScoverageScala.logging.level = LogLevel.DEBUG
```

Then look for the scalac task options:

>20:46:07.118 [DEBUG] [org.gradle.api.internal.tasks.scala.AntScalaCompiler] Ant scalac task options: {destDir=/Users/stu/Documents/Eclipse/gradle-scoverage-sample/single/build/classes/scoverage, target=jvm-1.7, fork=false, scalacdebugging=false, unchecked=on, force=never, addparams="-Xplugin:/Users/stu/.gradle/caches/modules-2/files-2.1/org.scoverage/scalac-scoverage-plugin_2.11/1.0.4/aec5ce1cc4fe0ed4ceb9691d399791e713b9a40f/scalac-scoverage-plugin_2.11-1.0.4.jar" "-P:scoverage:dataDir:/Users/stu/Documents/Eclipse/gradle-scoverage-sample

Are you loading other plugins, or perhaps providing scalac additionalParams?

Thanks,
Stu

**Comment by maiflai** [comment]
Hi Cory - do you have any updates on this please?

Thanks,
Stu

**Comment by coryfklein** [comment]
Sorry, no. I've been working on a separate project for the time being and
haven't had a chance to move back to this one yet. If you need to you can
close the issue for now and I'll reopen it when I have more information to
add. Probably will be a month or two.

**Comment by coryfklein** [comment]
I'm probably not going to get around to this any time soon, closing now. I'll reopen if/when I come back to it.
