### ISSUE TITLE
Joint Compilation of Java & Scala code

### ISSUE THREAD

**Issue by skrawcz** [scoverage/gradle-scoverage#55]
Hi, 

I have a case where `reportScoverage` fails; compilation fails because I have Java code that depends on Scala code. As far as I'm aware, compilation works just fine with the default gradle scala-plugin.

I have the standard setup of scala src being under one directory, and java src being under another directory.

Any ideas or pointers on how to get around this?

Cheers, 

Stefan

**Comment by maiflai** [comment]
Hi,

Yes, the scoverage compiler plugin appears to wipe the classes directory. If you have java code then you'll need to modify the scoverage scala source directories to include it.

I suspect this should be done automatically, but in the meantime:

```groovy
sourceSets.scoverage.scala.srcDir 'src/main/java'
```

Please could you let me know how you get on?

Thanks,
Stu

**Comment by skrawcz** [comment]
Ok cool thanks for the suggestion. I instead just took the route of merging my java and scala source directories - and that has solved my problem too. Feel free to close this if you like :)

Cheers,

Stefan
