### ISSUE TITLE
Scoverage on scalatest now working 

### ISSUE THREAD

**Issue by SimplyAmuthan** [scoverage/gradle-scoverage#58]
Hi,

I am trying to use scalatest + scoverage + gradle

here is my build.gradle 

`plugins {
    id "org.scoverage" version "2.1.0"
}

dependencies {
    scoverage   'org.scoverage:scalac-scoverage-plugin_2.12:1.3.0',
                        'org.scoverage:scalac-scoverage-runtime_2.12:1.3.0'
}`

and I am having all my scalatest clasess under src/test/scala something like 

`
class sampleTest extends FlatSpec with Matchers{
`

when I issue the command `gradle reportScoverage`

the reports are generated under `/build/reports/scoverage/index.html` file, but it is showing 0% for every class? what just I missed, is anyone have a successfully configured scoverage with scalatest ?

**Comment by maiflai** [comment]
Hi,

I think Gradle still requires a plugin to support scalatest - please could you try including https://plugins.gradle.org/plugin/com.github.maiflai.scalatest in your build?

Disclaimer - I'm also the author of that plugin, but I'm not aware of any others.

Thanks,
Stu.

**Comment by maiflai** [comment]
Hi,

Please can I close this issue if you have no further feedback?

Thanks,
Stu

**Comment by SimplyAmuthan** [comment]
let me try this this weekend and will let you know...

**Comment by maiflai** [comment]
Hi,

I'll close this issue tomorrow if there is no further feedback.

Thanks,
Stu

**Comment by SimplyAmuthan** [comment]
Hi it is working after adding the scalatest plugin.. here is my configuration 

```
plugins {
    id "com.github.maiflai.scalatest" version "0.15"
    id "org.scoverage" version "2.1.0"
}
dependencies {
    scoverage  "org.scoverage:scalac-scoverage-plugin_2.11:1.1.0",
                       "org.scoverage:scalac-scoverage-runtime_2.11:1.1.0"
}
```
