### ISSUE TITLE
Scala 2.12?

### ISSUE THREAD

**Issue by ches** [scoverage/gradle-scoverage#59]
Hi, I'm recently finding myself in a situation of Scala projects built with Gradle, which is unfamiliar territory for me… I want to upgrade some to 2.12 and the scoverage plugin is a stumbling block.

The plugin itself is written in Groovy but I suppose the test suite would need to cross-build, then publishing needs to also include two artifacts depending on the respective versions of `scalac-scoverage-plugin`—does that sum it up?

Gradle's Scala plugin doesn't appear to have native support for cross-building, have you done it on any projects with an approach you prefer?

**Comment by maiflai** [comment]
Hi,

Yes, I've usually defined an `ext` property for the scala version, and then used the gradle build task to define a task that executes the nested build with the appropriate version.

You can inspect the value of the property when defining `dependencies` (which include the scoverage dependencies).

Do you have a sample project that I could suggest changes to?

Thanks,
Stu

**Comment by ches** [comment]
Ah, I've misunderstood—I was thinking that gradle-scoverage itself needed to publish an updated artifact for different `scalac-scoverage-plugin` versions, but I realize now that that's what

```groovy
dependencies {
    scoverage '<possibly _2.12 artifact>'
}
```

is designed to support.

I'll give it a shot with this realization in mind. Thanks!

**Comment by maiflai** [comment]
No worries, let me know if you get stuck.

Cheers,
Stu
