### ISSUE TITLE
No test is executed with gradle 4.0

### ISSUE THREAD

**Issue by sinwe** [scoverage/gradle-scoverage#61]
It doesn't execute any test after upgrading to gradle 4.0

**Comment by maiflai** [comment]
Hi,

I notice that you are also using the gradle-scalatest plugin. Perhaps this is a duplicate of https://github.com/maiflai/gradle-scalatest/issues/50#issuecomment-309302686?

Please could you confirm?

Thanks,
Stu

**Comment by sinwe** [comment]
Yes, I do. But I think my scalatest are still executing the test. I could be wrong but I'll need to check it out.

**Comment by maiflai** [comment]
Please can I close this ticket as it doesn't appear related to the gradle-scoverage plugin?

**Comment by sinwe** [comment]
So are you saying that if scalatest is working, this will automatically work?

**Comment by maiflai** [comment]
In general, a common problem found when running `test` or `testScoverage` would be a problem with the underlying gradle-scalatest plugin.

A problem running `testScoverage` points to a problem with this plugin.

**Comment by sinwe** [comment]
Ok, understand. I'll close this then
