### ISSUE TITLE
Using scoverage for both java and scala source?

### ISSUE THREAD

**Issue by dyzhou222** [scoverage/gradle-scoverage#62]
Hello, I have both java and scala files (src/main/java/ and src/main/scala) and unit tests (src/test/java/ and src/test/scala/), and would like to use scoverage to collect code coverage for both, is this doable?  If so, could anyone please share a sample gradle snippet for doing that?  Thank you in advance.

**Comment by maiflai** [comment]
Hi,

Sorry, scoverage only supports scala.

You might consider using Jacaco? Unfortunately this will cover both Java and Scala because it works on bytecode.

Depending on your package structure it might be straightforward to exclude Scala code from the Jacoco results.

Hope this helps,
Stu.

**Comment by dyzhou222** [comment]
Hi @maiflai yes jacoco worked for me, thanks.

**Comment by maiflai** [comment]
Great, closing the issue then.

Thanks,
Stu
