### ISSUE TITLE
java.lang.ClassNotFoundException: scala.tools.nsc.transform.TypingTransformers$class

### ISSUE THREAD

**Issue by wheelerlaw** [scoverage/gradle-scoverage#63]
Snippet:
```
Caused by: java.lang.NoClassDefFoundError: scala/tools/nsc/transform/TypingTransformers$class
        at scoverage.ScoverageInstrumentationComponent.<init>(plugin.scala:54)
        at scoverage.ScoveragePlugin.<init>(plugin.scala:17)
```
Full stacktrace:
[pastebin](https://pastebin.com/sZUe5xn9)

`build.gradle` summary:
- `classpath "org.scoverage:gradle-scoverage:2.1.0"` in my buildscript dependencies.
- `apply plugin: 'org.scoverage'` as a top-level declaration in the `build.gradle`.
- `scoverage 'org.scoverage:scalac-scoverage-plugin_2.11:1.1.0', 'org.scoverage:scalac-scoverage-runtime_2.11:1.1.0'` in the main dependencies. 
- `compile 'org.scala-lang:scala-library:2.12.4'` and `compile 'org.scala-lang:scala-reflect:2.12.4'` in my main dependencies. 

I ran `gradle build` from my project directory and got that error. 
I noticed that `scala.tools` is not part of the standard scala library, so I'm not sure why scoverage would be referencing that without including it as a transitive dependency. Any help would be great, thanks.

**Comment by maiflai** [comment]
It looks as though you have mixed your scala dependencies: you're using a 2.12 scala-library with a 2.11 scoverage plugin.

If you're targetting 2.12 you should change your scoverage dependencies to contain `_2.12` rather than `_2.11`.

**Comment by wheelerlaw** [comment]
Yup, that did it. Thanks for the help.

**Comment by maiflai** [comment]
No problem, glad it's sorted.
