### ISSUE TITLE
gradle scoverage skipping reportScoverage

### ISSUE THREAD

**Issue by knarayanan88** [scoverage/gradle-scoverage#64]
Hi

We have a multi-module gradle scala project. I have multiple modules like 

    core/src/main/scala
    core/src/main/java
    core/src/test/scala
    core/src/test/java
    core/build.gradle
    common/...
    integration-tests/...
    build.gradle

I am trying to generate scoverage report using ./gradlew :core:test :core:reportScoverage, but it ends up running all the tests in core module but SKIPS the reportScoverage step and does not produce the directory 
`core/build/reports/scoverage`

    Run completed in 5 minutes, 44 seconds.
    Total number of tests run: 161
    Suites: completed 52, aborted 0
    Tests: succeeded 161, failed 0, canceled 0, ignored 0, pending 0
    All tests passed.

    :core:testScoverage UP-TO-DATE
    :core:testScoverage (Thread[Daemon worker,5,main]) completed. Took 0.13 secs.
    :core:reportScoverage (Thread[Daemon worker,5,main]) started.
    :core:reportScoverage
    Skipping task ':core:reportScoverage' as task onlyIf is false.
    :core:reportScoverage SKIPPED
    :core:reportScoverage (Thread[Daemon worker,5,main]) completed. Took 0.001 secs.

    BUILD SUCCESSFUL

    Total time: 6 mins 40.96 secs

The directories under build are : 
    
    build/tmp
    build/classes/scoverage/com/xyz/..
    build/classes/testScoverage/com/xyz/..
    build/reports/testScoverage/com/xyz/..
    ...

We use Gradle 3.0 with Scala 2.11.8
Parent build.gradle contains following related to scoverage : 

    buildscript {
        repositories {
            mavenLocal()
            mavenCentral()
        }

        dependencies {
            classpath "gradle.plugin.org.scoverage:gradle-scoverage:2.1.0"
        }
    }

    plugins {
        id "org.scoverage" version "2.1.0" apply false
    }

    subprojects { subproject ->
        apply plugin: "org.scoverage"    
        dependencies {
               scoverage scala('org.scoverage:scalac-scoverage-plugin:1.3.1'), scala('org.scoverage:scalac-scoverage-runtime:1.3.1')  
       }

        test {
            workingDir = rootDir
        }
        testScoverage {
            workingDir = rootDir
        }
    }

Could you let me know if we are missing something ? Why is reportScoverage getting SKIPPED. I wonder if the previous steps is generating the correct scoverage files for the reportScoverage step to read it and create the report.

**Comment by knarayanan88** [comment]
I tried upgrading gradle to 4.3 and also scalatest to 0.18.
But ./gradlew :core:reportScoverage is getting SKIPPED again after all tests run and succeed.

>:core:reportScoverage (Thread[Task worker for ':',5,main]) started.
 Task :core:reportScoverage SKIPPED
Skipping task ':core:reportScoverage' as task onlyIf is false.
:core:reportScoverage (Thread[Task worker for ':',5,main]) completed. Took 0.002 secs.

This time I see the `classes` folder under `core/build` is having one directory for `scala` and one for `java`. So seems good there.
But under reports it is only 
    
    core/build/reports/tests/
    core/build/reports/testScoverage/

I don't see scoverage folder here.

**Comment by maiflai** [comment]
Strange.

reportScoverage is skipped when there are no measurements to report.

testScoverage runs your normal tests against instrumented classes to produce these measurements.

It’s odd to see that testScoverage thinks it is up-to-date; I expect this is why there are no measurements.

Can you also run :core:clean and see if this runs the tests?

You shouldn’t need to run ‘test’ unless you are concerned that the instrumentation process will break your code.

Was this working before? What other changes have you made?

**Comment by knarayanan88** [comment]
So the testScoverage is running fine. When I run 
    ./gradlew clean  :core:reportScoverage
it runs all the tests but SKIPS reportScoverage. 

    Run completed in 6 minutes, 1 second.
    Total number of tests run: 161
    Suites: completed 52, aborted 0
    Tests: succeeded 161, failed 0, canceled 0, ignored 0, pending 0
    All tests passed.
    :core:testScoverage (Thread[Task worker for ':',5,main]) completed. Took 6 mins 2.548 secs.
    :core:reportScoverage (Thread[Task worker for ':',5,main]) started.

    Task :core:reportScoverage SKIPPED
    Skipping task ':core:reportScoverage' as task onlyIf is false.

    :core:reportScoverage (Thread[Task worker for ':',5,main]) completed. Took 0.003 secs.

    BUILD SUCCESSFUL in 7m 16s
    17 actionable tasks: 17 executed
    Stopped 1 worker daemon(s).

I can also see the testScoverage result files under `core/build/`. 

So I noticed that there was one java class in our repo. I read in [here](https://github.com/scoverage/gradle-scoverage/issues/62 ) that scoverage is supported only for scala. So I converted that java class into scala and tried running `./gradlew clean :core:reportScoverage`, but it is still getting SKIPPED.

My next question would be : Which directory does testScoverage write its measurement to?  I think there is a mismatch between where reportScoverage thinks the measurement files are and where the testScoverage is writing to. 

Any other thoughts ?

**Comment by maiflai** [comment]
The data directory is supposed to be called ‘scoverage’ and found in the build directory. The absolute path is used, so I wouldn’t expect issues from changing the working directory.

The data directory is injected by the compiler - running in debug mode should print the compiler flags for you to check?

**Comment by maiflai** [comment]
Possibly related to https://github.com/maiflai/gradle-scalatest/issues/50? If so likely to need a patch.

Sorry, will take a closer look later.

**Comment by knarayanan88** [comment]
I don't think it is related to Gradle 4.0. I was getting the same issue with Gradle 3.0 as well. 
I see the scoverage directory inside core/build/ but there are no files in it.
But I do see testScoverage htmls and xmls under 
    core/build/reports/tests/testScoverage/*.html and 
    core/build/test-results/testScoverage/*.xml 
core/build/reports/tests/testScoverage/ also has index.html and I can view the index.html in browser and it shows me 161 successful tests.

I still feel the reportScoverage is probably not configured to read where testScoverage is writing to. Is there any property that controls that configuration for both testScoverage and reportScoverage ?

I also feel this issue is similar to https://github.com/scoverage/gradle-scoverage/issues/52

**Comment by knarayanan88** [comment]
Following is some of debug logs after all Tests are run successfully : 

    20:23:14.781 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: SUCCEEDED
    20:23:14.788 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java'' finished with exit value 0 (state: SUCCEEDED)
    20:23:14.788 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Execute doLast {} action for :core:testScoverage'
    20:23:14.788 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Execute doLast {} action for :core:testScoverage' completed
    20:23:14.788 [DEBUG] [org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository] Snapshotting property binResultsDir (OUTPUT) for task ':core:testScoverage'
    20:23:14.789 [DEBUG] [org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository] Snapshotting property reports.enabledDirectoryReportDestinations.html for task ':core:testScoverage'
    20:23:14.845 [DEBUG] [org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository] Snapshotting property reports.enabledDirectoryReportDestinations.junitXml for task ':core:testScoverage'
    20:23:14.908 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter] Removed task artifact state for {} from context.
    20:23:14.908 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':core:testScoverage'
    20:23:14.908 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Task :core:testScoverage'
    20:23:14.908 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Task :core:testScoverage' completed
    20:23:14.908 [INFO] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] :core:testScoverage (Thread[Task worker for ':',5,main]) completed. Took 6 mins 10.005 secs.
    20:23:14.908 [DEBUG] [org.gradle.internal.work.DefaultWorkerLeaseService] Worker lease root.1.26 completed (1 worker(s) in use)
    20:23:14.908 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Task worker for ':': released lock on root.1.26
    20:23:14.908 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Task worker for ':': released lock on :
    20:23:14.909 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Task worker for ':': acquired lock on :
    20:23:14.909 [DEBUG] [org.gradle.internal.work.DefaultWorkerLeaseService] Worker lease root.1.26 started (1 worker(s) in use).
    20:23:14.909 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Task worker for ':': acquired lock on root.1.26
    20:23:14.909 [INFO] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] :core:reportScoverage (Thread[Task worker for ':',5,main]) started.
    20:23:14.909 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Task :core:reportScoverage' started
    20:23:14.909 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] :core:reportScoverage
    20:23:14.909 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker for ':' Thread 7,5,main]] finished, busy: 0.0 secs, idle: 8 mins 22.576 secs
    20:23:14.909 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':core:reportScoverage'
    20:23:14.909 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker for ':' Thread 3,5,main]] finished, busy: 0.0 secs, idle: 8 mins 22.577 secs
    20:23:14.909 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Daemon worker Thread 8,5,main]] finished, busy: 0.0 secs, idle: 8 mins 22.577 secs
    20:23:14.909 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker for ':' Thread 6,5,main]] finished, busy: 0.0 secs, idle: 8 mins 22.576 secs
    20:23:14.909 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker for ':' Thread 2,5,main]] finished, busy: 0.0 secs, idle: 8 mins 22.577 secs
    20:23:14.909 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker for ':' Thread 4,5,main]] finished, busy: 0.0 secs, idle: 8 mins 22.576 secs
    20:23:14.910 [INFO] [org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter] Skipping task ':core:reportScoverage' as task onlyIf is false.
    20:23:14.910 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':core:reportScoverage'
    20:23:14.910 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] :core:reportScoverage SKIPPED
    20:23:14.910 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Task :core:reportScoverage'
    20:23:14.910 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Task :core:reportScoverage' completed
    20:23:14.910 [INFO] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] :core:reportScoverage (Thread[Task worker for ':',5,main]) completed. Took 0.001 secs.
    20:23:14.910 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker for ':' Thread 5,5,main]] finished, busy: 0.0 secs, idle: 8 mins 22.576 secs
    20:23:14.910 [DEBUG] [org.gradle.internal.work.DefaultWorkerLeaseService] Worker lease root.1.26 completed (1 worker(s) in use)
    20:23:14.910 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Task worker for ':': released lock on root.1.26
    20:23:14.910 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Task worker for ':': released lock on :
    20:23:14.910 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker for ':',5,main]] finished, busy: 8 mins 22.547 secs, idle: 0.031 secs
    20:23:14.911 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskGraphExecuter] Timing: Executing the DAG took 8 mins 22.612 secs
    20:23:14.911 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Run tasks'
    20:23:14.911 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Run tasks' completed
    20:23:14.911 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] 
    20:23:14.911 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] BUILD SUCCESSFUL in 8m 23s
    20:23:14.911 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] 17 actionable tasks: 17 executed
    20:23:14.911 [DEBUG] [org.gradle.internal.work.DefaultWorkerLeaseService] Worker lease root.1 completed (0 worker(s) in use)
    20:23:14.911 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker Thread 8: released lock on root.1

**Comment by knarayanan88** [comment]
Adding to above, I noticed that `scoverage.coverage.xml` is not getting generated and that is probably why reportScoverage is not able to see the measurements and generate reports.
I tried adding : 
    testScoverage.outputs.file "${buildDir}/scoverage/scoverage.coverage.xml"
    compileScoverageScala {
        outputs.file("${buildDir}/scoverage/scoverage.coverage.xml")
    }
But it is still not generating the scoverage.coverage.xml file. The folder `core/build/scoverage` is empty.

**Comment by maiflai** [comment]
Please could you check the resolved classpath  used by testScoverage, by examining the debug logs?

The instrumented classes should appear first.

Note that in a multi-module project only the current module is instrumented and recorded - are you expecting to see coverage for all?

**Comment by knarayanan88** [comment]
Searching through the debug logs, below was the first part of classpath for testScoverage.

    21:54:38.021 [DEBUG] [org.gradle.api.internal.tasks.scala.NormalizingScalaCompiler] Java compiler arguments: -source 1.8 -target 1.8 -d /Users/abc/git/xyz/core/build/classes/scala/testScoverage -g -sourcepath  -proc:none -XDuseUnsharedTable=true -classpath /Users/narkrish/git/devicegraph/core/build/classes/java/scoverage:/Users/abc/git/xyz/core/build/classes/scala/scoverage:/Users/abc/git/xyz/core/build/resources/scoverage:....

I am not seeing any logs pertaining to where the instrumentation file is being written in the DEBUG logs. 
The `gradle-scoverage-sample` project has below lines, but my project `xyz` doesn't have the below lines in the debug logs.

    22:41:53.928 [QUIET] [system.out] [info] Beginning coverage instrumentation
    22:41:53.955 [QUIET] [system.out] [info] Instrumentation completed [1 statements]
    22:41:53.981 [QUIET] [system.out] [info] Wrote instrumentation file [/Users/abc/git/gradle-scoverage-sample/single/build/scoverage/scoverage.coverage.xml]
    22:41:53.981 [QUIET] [system.out] [info] Will write measurement data to [/Users/abc/git/gradle-scoverage-sample/single/build/scoverage]

I am expecting to see coverage for all modules as per the project [gradle-scoverage-sample](https://github.com/scoverage/gradle-scoverage-sample) , but for now I am trying to generate scoverage report for the `core` module.

What else would you like to see from the debug logs to help resolving this issue ?

**Comment by maiflai** [comment]
Sorry, that’s the compiler task rather than the testScoverage task.

We need to see that scalatest is being invoked with the instrumented classes.

Perhaps you could post the debug log as a gist?

**Comment by knarayanan88** [comment]
@maiflai : Here is the gist of debug logs : https://gist.github.com/knarayanan88/60a489e4e7b7a64d316c0a068572cfbe

**Comment by knarayanan88** [comment]
Hi, Any update on this ?

**Comment by maiflai** [comment]
Looks like a bug exposed by mixed java/Scala projects but I’ve not had a chance to reproduce this locally.

Hope to get something done by Monday, but responding to threads is easier than writing code, sorry.

**Comment by knarayanan88** [comment]
I think I converted everything to scala and tried, but was still not generating the scoverage.coverage.xml.. Maybe I sent you an old debug log file ?

**Comment by maiflai** [comment]
Sorry - think I misinterpreted the log on first reading.

I don't see the expected compiler flag being passed - you should see a line like

> -P:scoverage:dataDir:/Users/stu/Documents/Source/gradle-scoverage-sample/single/build/scoverage

Please could you share the repository, or reproduce the issue with a repository that can be shared? 

Thanks,
Stu

**Comment by maiflai** [comment]
Perhaps you are setting your own compiler flags?

**Comment by knarayanan88** [comment]
I do see the following in `build.gradle` : https://gist.github.com/knarayanan88/a68c1a5989b0908f9bdb11de85029699 

Not sure if this is overwriting the compiler flags. What do you think ? 
If not, I will have to try this in a separate repo which can be shared. Will work on it early next week.

**Comment by knarayanan88** [comment]
I think you were right! I removed that part from my `build.gradle` and I see testScoverage and reportScoverage working fine. I am able to generate the reports.
This is great finding. Thanks @maiflai ! 
Now I need to see why that compiler settings were added and what is the repercussion of removing that from my build.gradle. If we need to retain it, would adding the scoverage settings also work ?

**Comment by maiflai** [comment]
Great - those options don’t look controversial but you might consider writing a function that appends them if necessary?

The problem is that you are overwriting the list of parameters after the scoverage plugin has appended its configuration.

**Comment by knarayanan88** [comment]
I see it has `scalaCompileOptions.setAdditionalParameters(scalacOptions)`, so isn't it appending to existing ?

**Comment by maiflai** [comment]
These are additional to the required parameters.

I think it’s conventional to use add/remove in that situation.

I think the reason it breaks in your project is that you are using the delayed closure to modify the parameters.

**Comment by knarayanan88** [comment]
Did you mean `gradle.projectsEvaluated ` ? I used the same in `gradle-scoverage-sample` project, but was not able to reproduce it.

**Comment by maiflai** [comment]
Did you try that with a multi-module project and `tasks.withType(ScalaCompile)`?

**Comment by knarayanan88** [comment]
I added : 

    gradle.projectsEvaluated {
        // Scala compiler options
        tasks.withType(ScalaCompile) {
            def scalacOptions = ["-deprecation", "-unchecked", "-feature", "-encoding", "UTF-8", "-Yclosure-elim", "-Yinline-warnings", "-Yinline"]
                if (versions.scalaMajor == "2.10") {
                    scalacOptions += ["-Xverify", "-Xlint", "-language:postfixOps", "-language:implicitConversions", "-language:higherKinds"]
                }
                scalaCompileOptions.setAdditionalParameters(scalacOptions)
        }
    }
in https://github.com/scoverage/gradle-scoverage-sample/blob/master/build.gradle

**Comment by maiflai** [comment]
With which version of Gradle? Are they using the same wrapped version?

**Comment by maiflai** [comment]
I expect that there is a subtle race condition when both the plugin and your closure are trying to set the list of additional parameters. 

I hope that in any given project it is deterministic based on the order of declaration, but I have seen interesting behaviour when using apply vs the new plugins api.

Please try to modify the list rather than replace it in your project?

**Comment by knarayanan88** [comment]
Gradle version is 4.0.  

    $ gradle -v 

    Gradle 4.0

    Build time:   2017-06-14 15:11:08 UTC
    Revision:     316546a5fcb4e2dfe1d6aa0b73a4e09e8cecb5a5

    Groovy:       2.4.11
    Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
    JVM:          1.8.0_131 (Oracle Corporation 25.131-b11)
    OS:           Mac OS X 10.12.4 x86_64

    $ ./gradlew -v

    Gradle 4.3.1

    Build time:   2017-11-08 08:59:45 UTC
    Revision:     e4f4804807ef7c2829da51877861ff06e07e006d

    Groovy:     2.4.12
    Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
    JVM:        1.8.0_131 (Oracle Corporation 25.131-b11)
    OS:          Mac OS X 10.12.4 x86_64

Could you explain how to modify the list ? Also I am not sure how where I am replacing it.

**Comment by knarayanan88** [comment]
@maiflai : Any suggestions ?

**Comment by maiflai** [comment]
` scalaCompileOptions.setAdditionalParameters(scalacOptions)`

This line replaces any existing additional compilation parameters with your custom list.

You might consider checking the contents of any existing list before overwriting it?

I think the path of least resistance here is for me to change the plugin to be even more delayed than it currently is.

**Comment by knarayanan88** [comment]
Thanks @maiflai . 
I added:  if getAdditionalParameters is not null , then add it to the list before overwriting and it works!. 
I am closing this issue.

**Comment by maiflai** [comment]
Thanks, glad to hear the problem is resolved
