### ISSUE TITLE
Plugin not found

### ISSUE THREAD

**Issue by ravindrabajpai** [scoverage/gradle-scoverage#65]
I followed this -
https://plugins.gradle.org/plugin/org.scoverage

and get this -
Caused by: org.gradle.api.plugins.UnknownPluginException: Plugin with id 'scoverage' not found.

This is I have in my build configurations - 
dependencies {
    classpath "gradle.plugin.org.scoverage:gradle-scoverage:2.1.0"
}

and this gives error -
    apply plugin: "org.scoverage"

why readme (https://github.com/scoverage/gradle-scoverage) says to have this -
dependencies {
    scoverage 'org.scoverage:scalac-scoverage-plugin_2.11:1.1.0', 'org.scoverage:scalac-scoverage-runtime_2.11:1.1.0'
}
which is different in - https://plugins.gradle.org/plugin/org.scoverage.

If I follow readme I get this error - 
Could not find method scoverage() for arguments [org.scoverage:scalac-scoverage-plugin_2.11:1.1.0, org.scoverage:scalac-scoverage-runtime_2.11:1.1.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

Which one to follow?

Not sure If I am missing here as I am new to gradle. Appreciate any help with this

**Comment by maiflai** [comment]
I think that in your gradle file

>dependencies {
classpath "gradle.plugin.org.scoverage:gradle-scoverage:2.1.0"
}

should be 
```groovy
buildscript {
  dependencies {
    classpath "gradle.plugin.org.scoverage:gradle-scoverage:2.1.0"
  }
}
```

Or you can use the ```plugins``` syntax which is simpler but only works for simple projects.

The ```buildscript``` ```dependencies``` block is required to enable the gradle plugin, but the other ```dependencies``` block configures scoverage itself.

This is to enable users to upgrade scoverage independently of the gradle plugin (which changes very infrequently).

Sorry for the delay,
Stu

**Comment by ravindrabajpai** [comment]
Thanks, I will try this.

**Comment by maiflai** [comment]
Please can I close this issue?

Thanks,
Stu

**Comment by ravindrabajpai** [comment]
Thanks
