### ISSUE TITLE
scalatest + scoverage reports 0% coverage

### ISSUE THREAD

**Issue by mmotoyama** [scoverage/gradle-scoverage#76]
Gradle noob here, and I'm not sure where to post this. I'm trying to integrate scoverage with a project that uses scalatest, but scoverage reports 0% coverage when I run reportScoverage.  I've reproduced the problem with the gradle-scoverage-sample setup, with the build.gradle file contents below (the only tweak being the inclusion of scalatest) modified for the singe app [example](https://github.com/scoverage/gradle-scoverage-sample/blob/master/single/build.gradle). Any advice here?

```
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
     classpath "gradle.plugin.com.github.maiflai:gradle-scalatest:0.19"
  }
}

apply plugin: 'scala'
apply plugin: "com.github.maiflai.scalatest"
apply plugin: 'org.scoverage'

repositories {
   mavenCentral()
}

dependencies {
   compile 'org.scala-lang:scala-library:2.11.4'
   compile 'commons-collections:commons-collections:3.2'
   testCompile 'junit:junit:4.11', 'org.scalatest:scalatest_2.11:3.0.1'
   testRuntime 'org.pegdown:pegdown:1.4.2'

   scoverage 'org.scoverage:scalac-scoverage-plugin_2.11:1.0.4', 'org.scoverage:scalac-scoverage-runtime_2.11:1.0.4'
}
```

**Comment by mmotoyama** [comment]
We figured out the issue in our build.gradle files. We had apparently integrated manually with scalatest and did not copy over the deferred test configuration performed [here](https://github.com/maiflai/gradle-scalatest/blob/master/src/main/groovy/com/github/maiflai/ScalaTestPlugin.groovy#L32):

```
t.tasks.withType(Test) { configure(it, factory) }
```

Thus, we needed to manually configure ```project.task.testScoverage``` with the ScalaTest runner [configuration](https://github.com/maiflai/gradle-scalatest/blob/master/src/main/groovy/com/github/maiflai/ScalaTestPlugin.groovy#L59). In terms of the example code, we needed to switch the test case to not use Junit (duh). Sorry for the hassle!

**Comment by maiflai** [comment]
Glad to hear it's working for you now.

Please could I ask why you have integrated manually with scalatest? Is there a missing feature, or a PR that you'd like to see merged there?

Thanks,
Stu

**Comment by mmotoyama** [comment]
I don't have the full context, but from what I understand based on the comments, we wanted to have the ability to run both Java and Scala tests in the same project. I noticed there are now modes in the scalatest plugin that will likely account for that case (possibly append? again, gradle beginner here), but I'm not sure that existed when we integrated with the plugin.

**Comment by maiflai** [comment]
Ok, no worries. If you are unable to use the new modes then please raise an issue over at https://github.com/maiflai/gradle-scalatest.

Thanks,
Stu.
