### ISSUE TITLE
Bump to Gradle 5.0

### ISSUE THREAD

**Issue by TobiasRoland** [scoverage/gradle-scoverage#86]
Hey, seeing as gradle 5.0 is now a full release, and the current version in the project is 4.7, we should probably consider upgrading

https://gradle.org/releases/

**Comment by maiflai** [comment]
Hi,

Yes, it looks like some of the test cases here are using an older API which means the upgrade is not a simple bump for this particular project.

However, this shouldn't stop gradle-scoverage users from upgrading their projects to 5.0. 

Are you having trouble using the published plugin?

Thanks,
Stu

**Comment by TobiasRoland** [comment]
Hi @maiflai - it's working fine with Gradle 5 as a client. Just wanted to raise that a Gradle 5 migration might be good since it makes the project look more up to date and active to potential users when they browse the repo browsing the repo. If I have some time over the holiday period I might attempt to do the upgrade and see what would need migrating - if that'd seems useful to other people than myself :)

**Comment by maiflai** [comment]
Fair point - I'll see if I can get around to it as it's relatively low-hanging fruit.

**Comment by maiflai** [comment]
Hi,

I've bumped the version to Gradle 5 and fixed the tests that were failing (due to test incompatibility, not main incompatibility).

Please can we close this ticket?

Thanks,
Stu.

**Comment by TobiasRoland** [comment]
Awesome stuff 👍
