### ISSUE TITLE
How to check branch and statement coverage in 3.0?

### ISSUE THREAD

**Issue by dsilvasc** [scoverage/gradle-scoverage#93]
In 2.x, we could have our builds check both branch and statement coverage:

```kotlin
val checkBranchCoverage = tasks.register("checkBranchCoverage", OverallCheckTask::class.java) {
  dependsOn(reportScoverage)
  coverageType = CoverageType.Branch
}

val checkStatementCoverage = tasks.register("checkStatementCoverage", OverallCheckTask::class.java) {
  dependsOn(reportScoverage)
  coverageType = CoverageType.Statement
}

val checkCoverage = tasks.register("checkCoverage") {
  dependsOn(checkStatementCoverage, checkBranchCoverage)
}
```

but since `coverageType` and `minimumRate` moved from the task config to the project config (in ScoverageExtension), this won't work anymore.

How can we check both in 3.x?

**Comment by maiflai** [comment]
Can you please provide the exact error message(s) that you see?

I've tried this with a simple groovy build, and I think the breaking change is that `reportDir` and `minimumRate` are not set on new instances of the `OverallCheckTask`.

> * What went wrong:
Some problems were found with the configuration of task ':checkStatementCoverage'.
> No value has been specified for property 'minimumRate'.
> No value has been specified for property '

Please could you try setting these manually?

```groovy
val checkStatementCoverage = tasks.register("checkStatementCoverage", OverallCheckTask::class.java) {
  dependsOn(reportScoverage)
  coverageType = CoverageType.Statement
  minimumRate = 1.0
  reportDir = checkScoverage.reportDir
}
```

**Comment by eyalroth** [comment]
I created a PR for a builtin support of this feature via this syntax:
```
scoverage {
  check {
    minimumRate = 0.1
    coverageType = CoverageType.Branch
  }
  check {
    minimumRate = 0.2
    coverageType = CoverageType.Statement
  }
}
```
