### ISSUE TITLE
scala-major resolution for 'implementation' configuration does not work

### ISSUE THREAD

**Issue by maslovalex** [scoverage/gradle-scoverage#96]
automatic scala-major-version resolution for scalac plugins does not work when scala-library defined as in dependesies like
`implementation "org.scala-lang:scala-library:2.11.12`

`compile` configuration is kind of deprecated, so I would expect more and more projects use `implementation`

**Comment by netvl** [comment]
BTW, same thing happens if Scala is added to the compileOnly configuration.

**Comment by eyalroth** [comment]
I created a PR to implement this. In the meanwhile, you could configure the version manually via the `scoverageScalaVersion` option ([see README](https://github.com/scoverage/gradle-scoverage#configuration)).
